name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repository

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@1685c3d8669829f192d94fcad89eba25ce558bb2

      - name: Build
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          cd $GITHUB_WORKSPACE/repository
          chmod +x gradlew
          ./gradlew publish
